### ISSUE TITLE
Suggestion: Use IFC IDs instead of Revit Guids

### ISSUE THREAD

**Issue by moethu** [MadsHolten/revit-bot-exporter#1]
Check out ExporterIFCUtils to generate IFC IDs from Revit elements:
Autodesk.Revit.DB.IFC.ExporterIFCUtils.CreateAlternateGUID(element);

**Comment by MadsHolten** [comment]
Awesome! Thank you for your contribution. I will have a look at it but unfortunately I am very busy these days - have to clear my desk before going on vacation.
